version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: shared_database
    restart: always
    environment:
      POSTGRES_USER: Exam
      POSTGRES_PASSWORD: Exam
      POSTGRES_DB: ExamProgramming
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
